package com.project.VISA.models.enums;

public enum TypeDemande {
    NOUVEAU_TITRE,
    RENOUVELLEMENT,
    DUPLICATA,
    TRANSFERT_VISA,
    RECUPERATION,
    NOUVEAU_TITRE_TRAVAILLEUR,
    NOUVEAU_TITRE_INVESTISSEUR,
    NOUVEAU_VISA_TRANSFORMABLE
}
